### ISSUE TITLE
NoWorkshop is not working

### ISSUE THREAD

**Issue by Cubody** [Ex-Presidents/CopiedLobbyMess#6]
The server is not shown in "No Workshop"

**Comment by Kr4ken-9** [comment]
I tested this and couldn't reproduce it, but I also only tested after the latest release.

I would suggest:
- Using the latest release: https://github.com/Ex-Presidents/CopiedLobbyMess/releases/tag/1.2.2
- Enabling MessConfig and HideWorkshop

I believe this issue is at least fixed in the latest release, so I'm going to close it. If not, feel free to comment and I will re-open it and investigate.
