### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by tofonek** [Ex-Presidents/CopiedLobbyMess#7]
Please update this plugin because it for now don't work so please update

**Comment by jonjon2420** [comment]
It works for the most part but you can't change the difficulty or the perspective, I can send you my code if that would help you at all.

**Comment by Kr4ken-9** [comment]
What are you entering for difficulty? Have you tried "EZY", "NRM", and "HRD"?
And for perspective? You could try "1Pp", "2Pp", "3Pp", or "4Pp"

**Comment by jonjon2420** [comment]
That actually completely fixed the issues I was having, thanks!

**Comment by Kr4ken-9** [comment]
I am closing this issue because the OP did not describe the problem at all which means I cannot investigate and fix the issue. If you comment with more information I will reopen the issue and look into fixing it.

Also, I will add some documentation to the README to hopefully prevent the secondary issue.
